# Generated by Django 3.2.3 on 2021-05-29 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210529_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='blog.category', verbose_name='Категория'),
        ),
    ]
