# Generated by Django 3.2.3 on 2021-05-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210529_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['title'], 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['is_published'], 'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Под-категории', 'verbose_name_plural': 'Под-категории'},
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.ManyToManyField(blank=True, related_name='companies', to='blog.City'),
        ),
    ]
