# Generated by Django 3.2.3 on 2021-05-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210530_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Город'),
        ),
    ]
